---
- name: Create New Virtual Machine
  hosts: localhost

  vars_files:
    - vcd-login.yml

  vars:
    # New VM Specifications
    - vcd_vdc: "vmware-vdc-test"
    - vcd_vm_name: "vApp1-VM-2"
    - vcd_vapp: "My-vApp1"
    - vcd_source_template_name: "CentOS-7-Template-Official"
    - vcd_source_vm_name: "vm-centos7"
    - vcd_vm_hostname: "mynewvm.localhost"
    - vcd_vm_password: "rootpass"
    - vcd_vm_network: "Network1"

  tasks:
  - name: create vapp vm from catalog
    vcd_vapp_vm:
      target_vm_name: "{{ vcd_vm_name }}"
      target_vapp: "{{ vcd_vapp }}"
      target_vdc: "{{ vcd_vdc }}"
      source_vdc: "{{ vcd_vdc }}"
      source_catalog_name: "Public Catalog"
      source_template_name: "{{ vcd_source_template_name }}"
      source_vm_name: "{{ vcd_source_vm_name }}"
      hostname: "{{ vcd_vm_hostname }}"
      vmpassword: "{{ vcd_vm_password }}"
      vmpassword_auto: "false"
      vmpassword_reset: "false"
      ip_allocation_mode: "DHCP"
      power_on: "true"
      all_eulas_accepted: "true"
      #storage_profile: "Standard"
      network: "{{ vcd_vm_network }}"
      #cust_script: "test_script"
      deploy: false
      state: "present"
      user: "{{ vcd_user }}"
      password: "{{ vcd_password }}"
      org: "{{ vcd_org }}"
      host: "{{ vcd_host }}"
      verify_ssl_certs: "{{ vcd_ssl }}"
...
