---
- name: Create New Virtual Machine
  hosts: localhost
  gather_facts: no

  vars_files:
    - vcd-login.yml

  vars:
    # New VM Specifications
    - vcd_vdc: "vmware-vdc-test"
    - vcd_vm_name: "vApp1-VM-2"
    - vcd_vapp: "My-vApp1"
    - vcd_source_catalog_name: "Public Catalog"
    - vcd_source_template_name: "CentOS-7-Template-Official"
    - vcd_source_vm_name: "vm-centos7"
    - vcd_vm_hostname: "mynewvm.localhost"
    - vcd_vm_password: "rootpass"
    - vcd_vm_network: "Network1"
    - vcd_ip_allocation_mode: "DHCP"
    - vcd_vm_ip_address: "10.10.30.19"
    - vcd_power_on: "false"

  tasks:
  - name: create vapp vm from catalog
    vcd_vapp_vm:
      target_vm_name: "{{ vcd_vm_name }}"
      target_vapp: "{{ vcd_vapp }}"
      target_vdc: "{{ vcd_vdc }}"
      source_vdc: "{{ vcd_vdc }}"
      source_catalog_name: "{{ vcd_source_catalog_name }}"
      source_template_name: "{{ vcd_source_template_name }}"
      source_vm_name: "{{ vcd_source_vm_name }}"
      hostname: "{{ vcd_vm_hostname }}"
      vmpassword: "{{ vcd_vm_password }}"
      vmpassword_auto: "false"
      vmpassword_reset: "false"
      all_eulas_accepted: "true"
      network: "{{ vcd_vm_network }}"
      ip_allocation_mode: "{{ vcd_ip_allocation_mode }}"
      power_on: "{{ vcd_power_on }}"
      deploy: false
      state: "present"
      user: "{{ vcd_user }}"
      password: "{{ vcd_password }}"
      org: "{{ vcd_org }}"
      host: "{{ vcd_host }}"
      verify_ssl_certs: "{{ vcd_ssl }}"

  - name: update nic with manual IP
    vcd_vapp_vm_nic:
      vm_name: "{{ vcd_vm_name }}"
      vapp: "{{ vcd_vapp }}"
      vdc: "{{ vcd_vdc }}"
      network: "{{ vcd_vm_network }}"
      ip_allocation_mode: MANUAL
      ip_address: "{{ vcd_ip_allocation_mode }}"
      state: update
...
