---
- name: Change Power State
  hosts: localhost
  gather_facts: no
  
  vars_files:
    - vcd-login.yml

  vars:
    - vcd_vdc: "vmware-vdc-test"    
    - vcd_vm_name: "vApp1-VM-2"
    - vcd_vapp: "My-vApp1"
    - vcd_operation: "poweron"

  tasks:
  - name: change power state on vm
    vcd_vapp_vm:
      target_vm_name: "{{ vcd_vm_name }}"
      target_vapp: "{{ vcd_vapp }}"
      target_vdc: "{{ vcd_vdc }}"      
      operation: "{{ vcd_operation }}"
      user: "{{ vcd_user }}"
      password: "{{ vcd_password }}"
      org: "{{ vcd_org }}"
      host: "{{ vcd_host }}"
      verify_ssl_certs: "{{ vcd_ssl }}"
...
