---
- name: Testing vCloud Director
  hosts: localhost

  vars_files:
    - vcd-login.yml

  vars:
    - vcd_vdc: "vmware-vdc-test"    
    - vcd_vm_name: "vApp1-VM-2"
    - vcd_vapp: "My-vApp1"    

  tasks:
  - name: delete vapp vm
    vcd_vapp_vm:
      target_vm_name: "{{ vcd_vm_name }}"
      target_vapp: "{{ vcd_vapp }}"
      target_vdc: "{{ vcd_vdc }}"    
      state: "absent"
      user: "{{ vcd_user }}"
      password: "{{ vcd_password }}"
      org: "{{ vcd_org }}"
      host: "{{ vcd_host }}"
      verify_ssl_certs: "{{ vcd_ssl }}"
...
